### ISSUE TITLE
consider renaming github repository

### ISSUE THREAD

**Issue by danmarsden** [plagiarismsearch/moodle-plagiarism_plagiarismsearch#2]
you may want to rename the repository here from "moodle" to something that fits the "frankenstyle" naming convention that is familiar to moodle site admins using github - this would be:
"moodle-plagiarism_plagiarismsearch"

obviously this is completely optional though so feel free to close as "won't fix" for whatever reason! :-)

**Comment by plagiarismsearch** [comment]
Ok! Good idea. Renamed to `plagiarismsearch/moodle-plagiarism_plagiarismsearch`.
